### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by AlexanderFox777** [AlexanderFox777/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by date7887** [comment]
####EXPERIENCE&HISTORY
<small>23 November 1963</small>
Doctor Who first appeared on BBC TV at 17:16:20 GMT on Saturday. This was eighty seconds later than the scheduled programme time, due to the assassination of John F. Kennedy the previous day.

<small>31 July 1963</small>
Whitaker commissioned Terry Nation to write a story under the title "The Mutants". As originally written, the Daleks and Thals were the victims of an alien neutron bomb attack but Nation later dropped the aliens and made the Daleks the aggressors.

<small>26 March 2005</small>
Doctor Who finally returned with the episode "Rose" on BBC One.

**Comment by AlexanderFox777** [comment]
Сперва нужно issues закрывать, а потом в телеграмм писать 🗡️
